### ISSUE TITLE
Back-end Implementation

### ISSUE THREAD

**Issue by SeanPrashad** [Mera-Gangapersaud/Creative-Collab#1]
As per offline discussion on Slack, @Mera-Gangapersaud would love to use [`MongoDB`](https://www.mongodb.com/) for the database with [`Node.js`](https://nodejs.org/en/download/) and [`Express`](https://expressjs.com/) for the web framework.

**Comment by SeanPrashad** [comment]
I have some experience using [`GraphQL`](https://graphql.github.io/) to replace multiple endpoints with a single one, allowing the client (whoever is querying the API), the request exactly the data they want.

Let's consider it a bonus task!

**Comment by humphd** [comment]
Oh man, don't listen to me.  I kid only those I love <3

**Comment by SeanPrashad** [comment]
**Note**: Check whose watching the repo next time
