### ISSUE TITLE
Integrate boardgame.io turns

### ISSUE THREAD

**Issue by SeanPrashad** [Mera-Gangapersaud/Creative-Collab#10]
With #8 landing, we can take it a step further to integrate [turn orders from boardgame.io](https://boardgame.io/#/turn-order).

What we aim to do is have one player enter text in a chatbox while the other is disabled. Once that same player has finished writing and added their text, focus should switch to the second player.

**Comment by pynnl** [comment]
I'll give this a shot if no one takes it

**Comment by SeanPrashad** [comment]
Great @pynnl!

We should look to enable the textbox for player one initially (think of them as the story creator). Textbox two should only be enabled after player one has sent their message (and vice versa).

Please don't hesitate to let us know if you have any questions - reach out to us here or on our [Slack](https://join.slack.com/t/creative-collab-app/shared_invite/enQtNDc2NjU3OTkxOTQxLWFiODBlMTBlZWUwODYwMTI5MzZkM2YzZGMxN2EzZTQzMGVlZDY5YjQxNWI1MmQxYjlhOTdkMTVjNmFmMzYyYjc)!

**Comment by SeanPrashad** [comment]
@dnguneratne We're happy to have a work in progress PR - Prefixing it with `[WIP]` would let the maintainers know that it's still being worked on. It would be great to see you and @pynnl team up for this!

Please let us know if there's any questions on what a possible solution for this issue might look like 🔎

**Comment by pynnl** [comment]
> I've been looking in to this for the past few days and I have a WIP PR I can open. @pynnl lets work on this together.

Yeah just checked out your PR, it's pretty cool and exactly what I'm thinking

**Comment by SeanPrashad** [comment]
With #20 merged into `master`, this can now be closed! 🎉
