### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by SeanPrashad** [Mera-Gangapersaud/Creative-Collab#12]
We should consider which license to include for Creative Collab. We could refer to [choosealicense.com](https://choosealicense.com/) for inspiration!

Any and all discussion welcome 🗣

**Comment by deepanjali19** [comment]
I think **MIT Licence** would be the best option as it provides all of the permissions we would need for this project.
Additionally, it explicitly states that it does NOT provide any warranty.

**I can add the licence if you want.**

**Comment by humphd** [comment]
If any of you decide you want to sell something based on this later, MIT is nice because it leaves the door open.  It's what I'd use if it were me.

**Comment by deepanjali19** [comment]
Sounds great @SeanPrashad ! I will get a PR up soon.

**Comment by SeanPrashad** [comment]
Fixed with #24
