### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by SeanPrashad** [Mera-Gangapersaud/Creative-Collab#22]
To prevent regressions, make our `npm test` command in TravisCI more meaningful, and add another layer of documentation, we should begin adding unit tests.

~We have some options for which route to take:~ Our option will be to use:

~* [Mocha](https://mochajs.org/)!~
* [Jest](https://jestjs.io/)

In my experience, using Jest has been pleasant to work with! ~easier but we're very open to either, as long as you can justify your choice!~

**Comment by pynnl** [comment]
I believe Jest is already included in react-scripts, based on [here](https://facebook.github.io/create-react-app/docs/running-tests)
![image](https://user-images.githubusercontent.com/31667324/48355703-a2f5c780-e662-11e8-90e1-88653081040e.png)

**Comment by CometS1** [comment]
I can try to make some test for this, what tests would you want, and how would you want them made?

**Comment by CometS1** [comment]
I tried to create a simple test that looks like this
```
import React from 'react';
import ReactDOM from 'react-dom';
import '../index.css';
import CreativeCollab from '../components/app';

it('renders without crashing', () => {
    ReactDOM.render(<CreativeCollab />, document.getElementById('root'));
  });
```
But when attempting to run it, I get the following error.
![image](https://user-images.githubusercontent.com/25065296/48656572-4abd1d80-e9f4-11e8-8568-5d0c6aed5fd3.png)
It states that the target container is not a DOM element. Do you know why?

**Comment by SeanPrashad** [comment]
cc @humphd @klymenkoo

**Comment by SeanPrashad** [comment]
I'm not sure about that error but we can look into Shallow rendering: https://facebook.github.io/create-react-app/docs/running-tests#option-1-shallow-rendering.

It will look something like:

```js
import React from 'react';
import { shallow } from 'enzyme';
import CreativeCollab from '../components/CreativeCollab';
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });

it('renders without crashing', () => {
  shallow(<CreativeCollab />);
});
```

**Comment by SeanPrashad** [comment]
We should definitely figure out that original error though - shallow rendering isn't the best route to go

**Comment by vldmrkl** [comment]
I will add tests for some components.

**Comment by CometS1** [comment]
@klymenkoo Can you try to determine how to test the app without shallow rendering?

**Comment by vldmrkl** [comment]
@CometS1 I'll take a look at it.

**Comment by vldmrkl** [comment]
@CometS1 You can use `mount` instead of `shallow`. This method renders full DOM.

However, I found out that it fails because of `React-Quill` component we import from an external library, and the only way to fix the test is to remove `React-Quill`.

You previous try fails for the same reason I assume:

> I tried to create a simple test that looks like this
> 
> ```
> import React from 'react';
> import ReactDOM from 'react-dom';
> import '../index.css';
> import CreativeCollab from '../components/app';
> 
> it('renders without crashing', () => {
>     ReactDOM.render(<CreativeCollab />, document.getElementById('root'));
>   });
> ```
> But when attempting to run it, I get the following error.
> ![image](https://user-images.githubusercontent.com/25065296/48656572-4abd1d80-e9f4-11e8-8568-5d0c6aed5fd3.png)
> It states that the target container is not a DOM element. Do you know why?
