### ISSUE TITLE
Travis Build is Failing

### ISSUE THREAD

**Issue by Mera-Gangapersaud** [Mera-Gangapersaud/Creative-Collab#27]
Travis is now failing. It worked initially when we had: 
```
before_script:
  - cd client && npm install
```

but that was just to adjust for caching node_modules outside of the client directory

now we removed `npm install` and the build fails because react-scripts is not found

![image](https://user-images.githubusercontent.com/21012099/48519713-dd668c80-e83b-11e8-8991-6e3af47fada0.png)

Should we just revert back to including `npm install`  or is there a better way to fix this?

See build [here](https://travis-ci.com/Mera-Gangapersaud/Creative-Collab/jobs/158669015)

**Comment by SeanPrashad** [comment]
I'll take this one on so it doesn't block any contributors
