### ISSUE TITLE
Investigate boardgame.io

### ISSUE THREAD

**Issue by Mera-Gangapersaud** [Mera-Gangapersaud/Creative-Collab#3]
[nicolodavis/boardgame.io ](https://github.com/nicolodavis/boardgame.io) has the turn based play functionality that we will need. Lets see if we can use that and strip out the unnecessary functionality that wont apply.

**Comment by humphd** [comment]
This looks *amazing*, great find.  This will get you to a working 0.1 really fast, nice work!

Also, some interesting opportunities to contribute upstream for the other external bugs people need for 0.3 and 0.4: https://github.com/nicolodavis/boardgame.io/issues

**Comment by SeanPrashad** [comment]
Skimming through the initial paragraph triggered me back to my microcontroller days with [state machines](https://en.wikipedia.org/wiki/Finite-state_machine).

**Comment by SeanPrashad** [comment]
Tutorial to go through: https://boardgame.io/#/tutorial

**Comment by SeanPrashad** [comment]
I've pushed a working example of [`connect four`](https://en.wikipedia.org/wiki/Connect_Four) to the `[boardgame.io-research](https://github.com/Mera-Gangapersaud/Creative-Collab/tree/boardgame.io-research)` branch.

Pull it down using `git fetch --all`, install dependencies using `npm i` and start it locally via `npm start`. Play around and see what you think!

**Comment by Mera-Gangapersaud** [comment]
We will proceed with using boardgame.io to build the app
